'use client';

import { useMemo, useState } from 'react';
import { Icon } from '@/components/Icon';
import { PetEditor } from '@/components/PetEditor';
import { useApp } from '@/components/AppProvider';
import type { Pet, RequestStatus } from '@/types';

type Section='overview'|'requests'|'schedule'|'clients'|'pets'|'reminders'|'broadcasts'|'analytics';
const nav:[Section,string,string][]=[['overview','layout','Обзор'],['requests','message','Заявки'],['schedule','calendar','Расписание'],['clients','users','Клиенты'],['pets','paw','Питомцы'],['reminders','bell','Напоминания'],['broadcasts','send','Рассылки'],['analytics','chart','Статистика']];

export function AdminApp(){
 const {state,savePet,setRequestStatus,sendReminder,resetDemo}=useApp(); const [section,setSection]=useState<Section>('overview'); const [query,setQuery]=useState(''); const [editor,setEditor]=useState<Pet|null>(null);
 const filtered=useMemo(()=>state.requests.filter(r=>(r.client+' '+r.petId).toLowerCase().includes(query.toLowerCase())),[state.requests,query]);
 const reset=()=>{if(window.confirm('Сбросить все demo-изменения?'))resetDemo()};
 return <>
  <div className="role-banner admin-role"><div><span className="eyebrow">ДЕМО-АДМИНКА</span><b>Интерфейс для сотрудников PET NIKA</b></div><button className="btn ghost" onClick={reset}>Сбросить demo</button></div>
  <div className="admin-layout"><aside className="admin-sidebar">{nav.map(([id,ic,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon name={ic}/><span>{label}</span></button>)}</aside><main className="admin-main">
   <div className="mobile-admin-nav">{nav.map(([id,,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</div>
   {section==='overview'&&<><AdminHead title="Обзор" subtitle="Операционная картина PET NIKA · demo data"/><div className="kpi-grid"><Kpi label="Новые заявки" value={String(state.requests.filter(r=>r.status==='Новая').length)} icon="message"/><Kpi label="Подтверждено" value={String(state.requests.filter(r=>r.status==='Подтверждена').length)} icon="calendar"/><Kpi label="Питомцев в базе" value={String(state.pets.length)} icon="paw"/><Kpi label="Напоминаний" value={String(state.reminders.filter(r=>!r.sent).length)} icon="bell"/></div><div className="admin-grid"><div className="card panel"><h3>Ближайшие визиты</h3>{state.requests.slice(0,4).map(r=><div className="mini-row" key={r.id}><div><b>{r.time} · {r.client}</b><small>{r.date}</small></div><span className={`status ${statusClass(r.status)}`}>{r.status}</span></div>)}</div><div className="card panel"><h3>Динамика обращений</h3><div className="bars">{[42,68,55,31,61,80,72].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div><small>Demo chart · 7 days</small></div></div></>}
   {section==='requests'&&<><AdminHead title="Заявки" subtitle="Поиск и смена статуса"/><div className="toolbar"><label className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Клиент или питомец"/></label></div><div className="table-card"><div className="table-row head"><span>Клиент</span><span>Услуга</span><span>Дата</span><span>Статус</span></div>{filtered.map(r=><div className="table-row" key={r.id}><span><b>{r.client}</b><small>{r.petId}</small></span><span>{r.serviceId}</span><span>{r.date}<small>{r.time}</small></span><select value={r.status} onChange={e=>setRequestStatus(r.id,e.target.value as RequestStatus)}>{['Новая','В обработке','Подтверждена','Завершена','Отменена'].map(s=><option key={s}>{s}</option>)}</select></div>)}</div></>}
   {section==='schedule'&&<><AdminHead title="Расписание" subtitle="Визиты и свободные интервалы"/><div className="card timeline">{['10:30','11:30','13:00','14:30','15:30'].map((t,i)=><div className="time-row" key={t}><b>{t}</b><div className={i===3?'free-slot':'appointment-slot'}>{i===3?'Свободное время':state.requests[i%state.requests.length]?.client+' · '+state.requests[i%state.requests.length]?.petId}</div></div>)}</div></>}
   {section==='clients'&&<><AdminHead title="Клиенты" subtitle="Контакты, питомцы и история"/><div className="entity-grid">{state.clients.map(c=><div className="card entity" key={c.id}><div className="entity-avatar">{c.name[0]}</div><h3>{c.name}</h3><p>{c.contact}</p><div className="entity-meta"><span>Визиты <b>{c.visits}</b></span><span>Следующий <b>{c.nextVisit}</b></span></div></div>)}</div></>}
   {section==='pets'&&<><AdminHead title="Питомцы" subtitle="Общая база и редактирование"/><div className="entity-grid">{state.pets.map(p=><button className="card entity pet-entity" key={p.id} onClick={()=>setEditor(p)}><div className="entity-avatar"><Icon name="paw"/></div><h3>{p.name}</h3><p>{p.owner} · {p.breed}</p><div className="entity-meta"><span>Вес <b>{p.weight}</b></span><span>PET ID <b>{p.petId}</b></span></div><span className="edit-link"><Icon name="edit"/>Редактировать</span></button>)}</div></>}
   {section==='reminders'&&<><AdminHead title="Напоминания" subtitle="Повторные визиты и профилактика"/><div className="table-card">{state.reminders.map(r=><div className="reminder-row" key={r.id}><div><b>{r.client} · {r.petId}</b><small>{r.reason} · {r.date} · {r.channel}</small></div><button className={`btn ${r.sent?'ghost':'primary'}`} disabled={r.sent} onClick={()=>sendReminder(r.id)}>{r.sent?'Отправлено':'Отправить'}</button></div>)}</div></>}
   {section==='broadcasts'&&<><AdminHead title="Рассылки" subtitle="Demo-сегментация и предпросмотр"/><div className="segments">{['Все клиенты','Владельцы собак','Владельцы кошек','Без визита 90+ дней','Скоро вакцинация','Выбранная группа'].map(x=><button className="card segment" key={x}>{x}</button>)}</div><div className="admin-grid"><div className="card panel"><label className="field"><span>Текст сообщения</span><textarea defaultValue="Напоминаем о плановой заботе о питомце. Откройте PET NIKA Mini App, чтобы выбрать удобное время."/></label><button className="btn primary">Отправить demo</button></div><div className="preview"><small>Предпросмотр</small><div className="bubble">Напоминаем о плановой заботе о питомце. Откройте PET NIKA Mini App, чтобы выбрать удобное время.</div></div></div></>}
   {section==='analytics'&&<><AdminHead title="Статистика" subtitle="Demo-аналитика будущей CRM"/><div className="kpi-grid"><Kpi label="Заявки за месяц" value="142" icon="message"/><Kpi label="Конверсия в визит" value="84%" icon="chart"/><Kpi label="Активные клиенты" value="128" icon="users"/><Kpi label="Повторные" value="64%" icon="paw"/></div><div className="card panel analytics"><h3>Популярные категории</h3>{[['Консультация',86],['Вакцинация',68],['Диагностика',52],['Процедуры',41]].map(([x,v])=><div className="metric" key={String(x)}><div><b>{x}</b><span>{v}</span></div><div className="metric-track"><span style={{width:`${v}%`}}/></div></div>)}</div></>}
  </main></div>
  <nav className="admin-bottom-nav">{nav.slice(0,5).map(([id,ic,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon name={ic}/><span>{label}</span></button>)}</nav>
  {editor&&<PetEditor admin pet={editor} onSave={savePet} onClose={()=>setEditor(null)}/>} 
 </>;
}
function AdminHead({title,subtitle}:{title:string;subtitle:string}){return <div className="admin-head"><h1>{title}</h1><p>{subtitle}</p></div>}
function Kpi({label,value,icon}:{label:string;value:string;icon:string}){return <div className="card kpi"><span className="icon-tile"><Icon name={icon}/></span><small>{label}</small><b>{value}</b></div>}
function statusClass(status:string){return status==='Новая'?'new':status==='Отменена'?'danger':'confirmed'}
