'use client';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { initialState } from '@/lib/demo-data';
import { loadState, resetStoredState, saveState } from '@/lib/storage';
import type { AppState, AppointmentRequest, Language, Pet, Reminder, RequestStatus } from '@/types';
interface AppContextValue { state: AppState; hydrated: boolean; setLanguage: (language: Language) => void; setActivePet: (id: string) => void; savePet: (pet: Pet) => void; addPet: (pet: Pet) => void; addRequest: (request: AppointmentRequest) => void; setRequestStatus: (id: string, status: RequestStatus) => void; sendReminder: (id: string) => void; resetDemo: () => void; }
const AppContext = createContext<AppContextValue | null>(null);
export function AppProvider({ children }: { children: React.ReactNode }) { const [state, setState] = useState<AppState>(initialState); const [hydrated, setHydrated] = useState(false); useEffect(() => { setState(loadState()); setHydrated(true); }, []); useEffect(() => { if (hydrated) saveState(state); }, [state, hydrated]); const value = useMemo<AppContextValue>(() => ({ state, hydrated, setLanguage: (language) => setState((s) => ({ ...s, language })), setActivePet: (activePetId) => setState((s) => ({ ...s, activePetId })), savePet: (pet) => setState((s) => ({ ...s, pets: s.pets.map((p) => p.id === pet.id ? pet : p) })), addPet: (pet) => setState((s) => ({ ...s, pets: [...s.pets, pet], activePetId: pet.id })), addRequest: (request) => setState((s) => ({ ...s, requests: [request, ...s.requests] })), setRequestStatus: (id, status) => setState((s) => ({ ...s, requests: s.requests.map((r) => r.id === id ? { ...r, status } : r) })), sendReminder: (id) => setState((s) => ({ ...s, reminders: s.reminders.map((r: Reminder) => r.id === id ? { ...r, sent: true } : r) })), resetDemo: () => { resetStoredState(); setState(structuredClone(initialState)); }, }), [state, hydrated]); return <AppContext.Provider value={value}>{children}</AppContext.Provider>; }
export function useApp() { const ctx = useContext(AppContext); if (!ctx) throw new Error('useApp must be used inside AppProvider'); return ctx; }
