import type { Language, RequestStatus } from '@/types';

export const copy = {
  ru: {
    roleClient:'Профиль клиента', roleAdmin:'Демо-админка', roleClientHint:'Интерфейс владельца питомца', roleAdminHint:'Интерфейс сотрудников PET NIKA',
    clientEyebrow:'ПРОФИЛЬ КЛИЕНТА', clientHint:'То, что видит владелец питомца', adminEyebrow:'ДЕМО-АДМИНКА', adminHint:'Интерфейс для сотрудников PET NIKA', reset:'Сбросить demo',
    hello:'Добрый день, Ольга', howToday:(name:string)=>`Как ${name} сегодня?`, heroText:'Всё важное о питомце — рядом, без лишней суеты.', book:'Записаться', repeat:'Повторить визит', ask:'Спросить',
    upcoming:'Ближайшая запись', august:'авг', routine:'Плановый осмотр', confirmed:'Подтверждено', quick:'Быстрые действия', services:'Услуги', servicesText:'Выберите повод визита', myPet:'Мой питомец', myPetText:'История, документы, заметки', storeText:'Реальная точка рядом', route:'Как добраться', reminders:'Напоминания', vaccinationCheck:'Проверить срок вакцинации', reminderText:'Система заранее показывает повод вернуться и позволяет записаться в один клик.', in24:'через 24 дня',
    servicesSubtitle:'Демо-категории. Актуальный официальный прайс публично не подтверждён.', booking:'Запись', bookingSubtitle:'Сценарий без длинной переписки.', petTitle:'Мой питомец', petSubtitle:'Данные владельца редактируются, данные клиники защищены.', addPet:'Добавить питомца', favourite:'Любимый питомец', edit:'Редактировать', weight:'Вес', sex:'Пол', reminder:'Напоминание', ownerData:'ДАННЫЕ ВЛАДЕЛЬЦА', clinicData:'ДАННЫЕ КЛИНИКИ', behavior:'Поведение', allergies:'Аллергии', notes:'Заметки', lastVisit:'Последний визит', health:'Особенности здоровья', clinicNote:'Заметка клиники', profile:'Профиль', profileSubtitle:'Записи, питомцы и связь с клиникой.', yourPet:'Ваш питомец', myPets:'Мои питомцы', myAppointments:'Мои записи', activeDemo:'1 активная · demo', repeatVisits:'вакцинации · повторные визиты', contactClinic:'Связаться с клиникой', channelPending:'реальный канал пока не подключён', home:'Главная', pet:'Питомец',
    chooseService:'Выберите услугу', choosePet:'Выберите питомца', specialist:'Специалист / вариант', specialistDemo:'Реальный список специалистов не подтверждён.', anySpecialist:'Любой доступный специалист', chooseDate:'Выберите дату', chooseTime:'Выберите время', contactComment:'Контакт и комментарий', phone:'Телефон / мессенджер', comment:'Комментарий', commentPlaceholder:'Что важно знать о питомце?', review:'Проверьте запись', service:'Услуга', date:'Дата', time:'Время', back:'Назад', next:'Далее', requestCreated:'Заявка создана', requestCreatedText:'В реальной системе администратор подтвердит время, а клиент увидит новый статус.', backHome:'На главную',
    overview:'Обзор', requests:'Заявки', schedule:'Расписание', clients:'Клиенты', petsAdmin:'Питомцы', broadcasts:'Рассылки', analytics:'Статистика', overviewSub:'Операционная картина PET NIKA · demo data', newRequests:'Новые заявки', confirmedCount:'Подтверждено', petsDb:'Питомцев в базе', reminderCount:'Напоминаний', upcomingVisits:'Ближайшие визиты', dynamics:'Динамика обращений', demoChart:'Demo chart · 7 days', requestsSub:'Поиск и смена статуса', searchPlaceholder:'Клиент или питомец', client:'Клиент', sourceService:'Услуга', status:'Статус', scheduleSub:'Визиты и свободные интервалы', freeTime:'Свободное время', clientsSub:'Контакты, питомцы и история', visits:'Визиты', nextVisit:'Следующий', petsSub:'Общая база и редактирование', remindersSub:'Повторные визиты и профилактика', sent:'Отправлено', send:'Отправить', broadcastsSub:'Demo-сегментация и предпросмотр', allClients:'Все клиенты', dogOwners:'Владельцы собак', catOwners:'Владельцы кошек', inactive90:'Без визита 90+ дней', vaccineSoon:'Скоро вакцинация', selectedGroup:'Выбранная группа', messageText:'Текст сообщения', broadcastMessage:'Напоминаем о плановой заботе о питомце. Откройте PET NIKA Mini App, чтобы выбрать удобное время.', sendDemo:'Отправить demo', preview:'Предпросмотр', analyticsSub:'Demo-аналитика будущей CRM', monthRequests:'Заявки за месяц', visitConversion:'Конверсия в визит', activeClients:'Активные клиенты', repeatClients:'Повторные', popularCategories:'Популярные категории',
    editorTitle:'Редактировать питомца', photo:'Фото питомца', choosePhoto:'Выбрать фото', name:'Имя *', species:'Вид *', breed:'Порода', birthDate:'Дата рождения', age:'Возраст', color:'Окрас', sterilized:'Стерилизован / кастрирован', owner:'Владелец', nextReminder:'Следующее напоминание', ownerNotes:'Заметки владельца', cancel:'Отмена', save:'Сохранить', requiredPet:'Заполните имя и вид',
    consult:'Консультация', vaccine:'Вакцинация', diagnostic:'Диагностика', procedure:'Процедуры'
  },
  en: {
    roleClient:'Client profile', roleAdmin:'Demo admin', roleClientHint:'Pet owner interface', roleAdminHint:'PET NIKA staff interface',
    clientEyebrow:'CLIENT PROFILE', clientHint:'What the pet owner sees', adminEyebrow:'DEMO ADMIN', adminHint:'PET NIKA staff interface', reset:'Reset demo',
    hello:'Good afternoon, Olga', howToday:(name:string)=>`How is ${name} today?`, heroText:'Everything important about your pet, close at hand and without the fuss.', book:'Book visit', repeat:'Repeat visit', ask:'Ask',
    upcoming:'Upcoming appointment', august:'Aug', routine:'Routine check-up', confirmed:'Confirmed', quick:'Quick actions', services:'Services', servicesText:'Choose a reason for the visit', myPet:'My pet', myPetText:'History, documents and notes', storeText:'Real store location nearby', route:'Directions', reminders:'Reminders', vaccinationCheck:'Check vaccination due date', reminderText:'The system shows a reason to return in advance and lets you book in one tap.', in24:'in 24 days',
    servicesSubtitle:'Demo categories. PET NIKA’s current official public price list has not been verified.', booking:'Booking', bookingSubtitle:'A booking flow without long messaging.', petTitle:'My pet', petSubtitle:'Owner data can be edited; clinic data stays protected.', addPet:'Add pet', favourite:'Favourite pet', edit:'Edit', weight:'Weight', sex:'Sex', reminder:'Reminder', ownerData:'OWNER DATA', clinicData:'CLINIC DATA', behavior:'Behavior', allergies:'Allergies', notes:'Notes', lastVisit:'Last visit', health:'Health notes', clinicNote:'Clinic note', profile:'Profile', profileSubtitle:'Appointments, pets and clinic communication.', yourPet:'Your pet', myPets:'My pets', myAppointments:'My appointments', activeDemo:'1 active · demo', repeatVisits:'vaccinations · repeat visits', contactClinic:'Contact clinic', channelPending:'real contact channel is not connected yet', home:'Home', pet:'Pet',
    chooseService:'Choose service', choosePet:'Choose pet', specialist:'Specialist / option', specialistDemo:'The real specialist list has not been verified.', anySpecialist:'Any available specialist', chooseDate:'Choose date', chooseTime:'Choose time', contactComment:'Contact and comment', phone:'Phone / messenger', comment:'Comment', commentPlaceholder:'What should the clinic know?', review:'Review booking', service:'Service', date:'Date', time:'Time', back:'Back', next:'Next', requestCreated:'Request created', requestCreatedText:'In production, the administrator confirms the time and the client sees the updated status.', backHome:'Back home',
    overview:'Overview', requests:'Requests', schedule:'Schedule', clients:'Clients', petsAdmin:'Pets', broadcasts:'Broadcasts', analytics:'Analytics', overviewSub:'PET NIKA operations · demo data', newRequests:'New requests', confirmedCount:'Confirmed', petsDb:'Pets in database', reminderCount:'Reminders', upcomingVisits:'Upcoming visits', dynamics:'Request dynamics', demoChart:'Demo chart · 7 days', requestsSub:'Search and status changes', searchPlaceholder:'Client or pet', client:'Client', sourceService:'Service', status:'Status', scheduleSub:'Visits and free slots', freeTime:'Free slot', clientsSub:'Contacts, pets and history', visits:'Visits', nextVisit:'Next', petsSub:'Shared database and editing', remindersSub:'Repeat visits and preventive care', sent:'Sent', send:'Send', broadcastsSub:'Demo segmentation and preview', allClients:'All clients', dogOwners:'Dog owners', catOwners:'Cat owners', inactive90:'No visit for 90+ days', vaccineSoon:'Vaccination due soon', selectedGroup:'Selected group', messageText:'Message text', broadcastMessage:'A reminder about planned pet care. Open PET NIKA Mini App to choose a convenient time.', sendDemo:'Send demo', preview:'Preview', analyticsSub:'Demo analytics for the future CRM', monthRequests:'Requests this month', visitConversion:'Visit conversion', activeClients:'Active clients', repeatClients:'Repeat clients', popularCategories:'Popular categories',
    editorTitle:'Edit pet', photo:'Pet photo', choosePhoto:'Choose photo', name:'Name *', species:'Species *', breed:'Breed', birthDate:'Birth date', age:'Age', color:'Color', sterilized:'Spayed / neutered', owner:'Owner', nextReminder:'Next reminder', ownerNotes:'Owner notes', cancel:'Cancel', save:'Save', requiredPet:'Enter pet name and species',
    consult:'Consultation', vaccine:'Vaccination', diagnostic:'Diagnostics', procedure:'Procedures'
  },
  vi: {
    roleClient:'Hồ sơ khách hàng', roleAdmin:'Quản trị demo', roleClientHint:'Giao diện chủ thú cưng', roleAdminHint:'Giao diện nhân viên PET NIKA',
    clientEyebrow:'HỒ SƠ KHÁCH HÀNG', clientHint:'Giao diện dành cho chủ thú cưng', adminEyebrow:'QUẢN TRỊ DEMO', adminHint:'Giao diện nhân viên PET NIKA', reset:'Đặt lại demo',
    hello:'Chào buổi chiều, Olga', howToday:(name:string)=>`${name} hôm nay thế nào?`, heroText:'Mọi thông tin quan trọng về thú cưng luôn ở ngay bên bạn.', book:'Đặt lịch', repeat:'Đặt lại lịch', ask:'Hỏi',
    upcoming:'Lịch hẹn sắp tới', august:'Thg 8', routine:'Khám định kỳ', confirmed:'Đã xác nhận', quick:'Thao tác nhanh', services:'Dịch vụ', servicesText:'Chọn lý do đến khám', myPet:'Thú cưng', myPetText:'Lịch sử, tài liệu và ghi chú', storeText:'Điểm bán thực tế gần phòng khám', route:'Chỉ đường', reminders:'Nhắc lịch', vaccinationCheck:'Kiểm tra lịch tiêm', reminderText:'Hệ thống báo trước lý do quay lại và cho phép đặt lịch nhanh.', in24:'sau 24 ngày',
    servicesSubtitle:'Các danh mục chỉ để minh họa. Bảng giá công khai hiện tại của PET NIKA chưa được xác minh.', booking:'Đặt lịch', bookingSubtitle:'Luồng đặt lịch không cần nhắn tin dài.', petTitle:'Thú cưng của tôi', petSubtitle:'Dữ liệu chủ nuôi có thể chỉnh sửa; dữ liệu phòng khám được bảo vệ.', addPet:'Thêm thú cưng', favourite:'Thú cưng yêu thích', edit:'Chỉnh sửa', weight:'Cân nặng', sex:'Giới tính', reminder:'Nhắc lịch', ownerData:'DỮ LIỆU CHỦ NUÔI', clinicData:'DỮ LIỆU PHÒNG KHÁM', behavior:'Hành vi', allergies:'Dị ứng', notes:'Ghi chú', lastVisit:'Lần khám gần nhất', health:'Ghi chú sức khỏe', clinicNote:'Ghi chú phòng khám', profile:'Hồ sơ', profileSubtitle:'Lịch hẹn, thú cưng và liên hệ phòng khám.', yourPet:'Thú cưng của bạn', myPets:'Thú cưng', myAppointments:'Lịch hẹn', activeDemo:'1 đang hoạt động · demo', repeatVisits:'tiêm phòng · tái khám', contactClinic:'Liên hệ phòng khám', channelPending:'kênh liên hệ thật chưa được kết nối', home:'Trang chủ', pet:'Thú cưng',
    chooseService:'Chọn dịch vụ', choosePet:'Chọn thú cưng', specialist:'Chuyên gia / lựa chọn', specialistDemo:'Danh sách chuyên gia thật chưa được xác minh.', anySpecialist:'Bất kỳ chuyên gia nào có lịch trống', chooseDate:'Chọn ngày', chooseTime:'Chọn giờ', contactComment:'Liên hệ và ghi chú', phone:'Điện thoại / messenger', comment:'Ghi chú', commentPlaceholder:'Phòng khám cần biết gì?', review:'Kiểm tra lịch', service:'Dịch vụ', date:'Ngày', time:'Giờ', back:'Quay lại', next:'Tiếp', requestCreated:'Đã tạo yêu cầu', requestCreatedText:'Trong hệ thống thật, quản trị viên xác nhận thời gian và khách hàng thấy trạng thái mới.', backHome:'Về trang chủ',
    overview:'Tổng quan', requests:'Yêu cầu', schedule:'Lịch', clients:'Khách hàng', petsAdmin:'Thú cưng', broadcasts:'Gửi tin', analytics:'Thống kê', overviewSub:'Hoạt động PET NIKA · dữ liệu demo', newRequests:'Yêu cầu mới', confirmedCount:'Đã xác nhận', petsDb:'Thú cưng trong hệ thống', reminderCount:'Nhắc lịch', upcomingVisits:'Lịch sắp tới', dynamics:'Động lực yêu cầu', demoChart:'Biểu đồ demo · 7 ngày', requestsSub:'Tìm kiếm và đổi trạng thái', searchPlaceholder:'Khách hàng hoặc thú cưng', client:'Khách hàng', sourceService:'Dịch vụ', status:'Trạng thái', scheduleSub:'Lịch khám và khoảng trống', freeTime:'Khoảng trống', clientsSub:'Liên hệ, thú cưng và lịch sử', visits:'Lần khám', nextVisit:'Tiếp theo', petsSub:'Cơ sở dữ liệu và chỉnh sửa', remindersSub:'Tái khám và chăm sóc phòng ngừa', sent:'Đã gửi', send:'Gửi', broadcastsSub:'Phân nhóm demo và xem trước', allClients:'Tất cả khách hàng', dogOwners:'Chủ chó', catOwners:'Chủ mèo', inactive90:'Không khám 90+ ngày', vaccineSoon:'Sắp đến lịch tiêm', selectedGroup:'Nhóm đã chọn', messageText:'Nội dung tin nhắn', broadcastMessage:'Nhắc bạn về kế hoạch chăm sóc thú cưng. Mở PET NIKA Mini App để chọn thời gian phù hợp.', sendDemo:'Gửi demo', preview:'Xem trước', analyticsSub:'Thống kê demo cho CRM tương lai', monthRequests:'Yêu cầu trong tháng', visitConversion:'Tỷ lệ đến khám', activeClients:'Khách đang hoạt động', repeatClients:'Khách quay lại', popularCategories:'Danh mục phổ biến',
    editorTitle:'Chỉnh sửa thú cưng', photo:'Ảnh thú cưng', choosePhoto:'Chọn ảnh', name:'Tên *', species:'Loài *', breed:'Giống', birthDate:'Ngày sinh', age:'Tuổi', color:'Màu lông', sterilized:'Đã triệt sản', owner:'Chủ nuôi', nextReminder:'Lần nhắc tiếp theo', ownerNotes:'Ghi chú của chủ', cancel:'Hủy', save:'Lưu', requiredPet:'Nhập tên và loài thú cưng',
    consult:'Tư vấn', vaccine:'Tiêm phòng', diagnostic:'Chẩn đoán', procedure:'Thủ thuật'
  }
} as const;

export function ui(language: Language){ return copy[language]; }

const statusMap: Record<Language, Record<RequestStatus,string>> = {
  ru:{'Новая':'Новая','В обработке':'В обработке','Подтверждена':'Подтверждена','Завершена':'Завершена','Отменена':'Отменена'},
  en:{'Новая':'New','В обработке':'In progress','Подтверждена':'Confirmed','Завершена':'Completed','Отменена':'Cancelled'},
  vi:{'Новая':'Mới','В обработке':'Đang xử lý','Подтверждена':'Đã xác nhận','Завершена':'Hoàn tất','Отменена':'Đã hủy'}
};
export function statusLabel(language:Language,status:RequestStatus){ return statusMap[language][status]; }

export function localizedPetValue(language:Language,value:string){
  const map: Record<Language,Record<string,string>> = {
    ru:{'Собака':'Собака','Кошка':'Кошка','Самец':'Самец','Самка':'Самка','4 года':'4 года','2 года':'2 года','Не указаны':'Не указаны'},
    en:{'Собака':'Dog','Кошка':'Cat','Самец':'Male','Самка':'Female','4 года':'4 years','2 года':'2 years','Не указаны':'Not specified'},
    vi:{'Собака':'Chó','Кошка':'Mèo','Самец':'Đực','Самка':'Cái','4 года':'4 tuổi','2 года':'2 tuổi','Не указаны':'Chưa ghi'}
  };
  return map[language][value] ?? value;
}
